name: actions_build_hyperos_port_mi10
on:
  workflow_dispatch:
    inputs:
      STOCK_URL:
        description: "BASEROM DIRECT DOWNLOAD LINK (XIAOMI.EU or CN OFFICIAL ROM)"
        required: true
        default: https://bkt-sgp-miui-ota-update-alisgp.oss-ap-southeast-1.aliyuncs.com/OS1.0.5.0.TJBCNXM/miui_UMI_OS1.0.5.0.TJBCNXM_d01651ed86_13.0.zip
      PORT_URL:
        description: "PORTROM DIRECT DOWNLOAD LINK (XIAOMI.EU OR CN OFFICIAL ROM)"
        required: true
        default: https://bkt-sgp-miui-ota-update-alisgp.oss-ap-southeast-1.aliyuncs.com/OS1.0.23.0.UNACNXM/miui_AURORA_OS1.0.23.0.UNACNXM_9bb4b476f4_14.0.zip
      PACK_TYPE:
        description: "PACKING TYPE (EXT/EROFS), EROFS BY DEFAULT"
        default: EXT
        type: choice
        options:
        - EROFS
        - EXT
        required: true
      ENCRYPTION:
        description: "FBE DECRYPTION OR NOT, FBE ENABLED BY DEFAULT"
        default: FALSE
        required: false
      ONEDRIVE:
        description: "PUSH ROM TO ONEDRIVE"
        default: FALSE
        required: false
      GITHUBRELEASE:
        description: "UPLOAD ROM TO GITHUB RELEASE"
        default: FALSE
        required: false

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: 1. MAXIMIZE BUILD SPACE
        uses: rokibhasansagar/slimhub_actions@main
        
      - name: 2. CHECKOUT REPOSITORY
        uses: actions/checkout@main
        with:
          ref: main
          fetch-depth: 1
      - name: 3. Setup Swap Size
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12
          
      - name: 4. PREPARE ENVIRONMENT
        run: |
          sudo apt install python3 aria2 zip p7zip-full zipalign android-sdk-libsparse-utils xmlstarlet
          sudo apt-get remove -y firefox zstd
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone/
          echo "${{ secrets.RCLONE_TOKEN }}" > token.txt
          base64 -d token.txt > ~/.config/rclone/rclone.conf
      - name: 5. START PORTING
        run: |
          git clone https://github.com/toraidl/hyperos_port.git -b test
          cd hyperos_port
          sudo chmod -R a+x . 
          mkdir tmp
          rclone sync -P onedrive:/ROM_FILES/ tmp/
          mkdir -p devices/umi devices/cmi
          cp -rfv tmp/BT*.zip devices/umi
          cp -rfv tmp/BT*.zip devices/cmi
          if [[ ${{ github.event.inputs.PACK_TYPE }} == "EROFS" ]]; then
              sed -i "s/repack_with_ext4=true/repack_with_ext4=false/" bin/port_config
          fi
          if [[ ${{ github.event.inputs.ENCRYPTION }} == "TRUE" ]]; then
              sed -i "s/remove_data_encryption=false/remove_data_encryption=true/" bin/port_config
          fi
          sudo timedatectl set-timezone Asia/Shanghai
          sed -i "s/pack_method=.*/pack_method=aosp/" port.sh
          sudo bash setup.sh
          sudo bash port.sh ${{ github.event.inputs.STOCK_URL }} ${{ github.event.inputs.PORT_URL }} 
      - name: 5. PREPARE UPLOADING
        run: |
          ROM_FILE=$(basename $(find "$GITHUB_WORKSPACE"/hyperos_port/out -name "*.zip" ! -name "target-files.zip"))
          echo "ROM_FILE=$ROM_FILE" >>$GITHUB_ENV
          OS_VERSION=$(echo $ROM_FILE | cut -d "_" -f3)
          echo "OS_VERSION=$OS_VERSION" >>$GITHUB_ENV
          mkdir -p "$GITHUB_WORKSPACE"/hyperos_port/GithubRelease
          cd "$GITHUB_WORKSPACE"/hyperos_port/GithubRelease
          sudo split -b 1536M -d "$GITHUB_WORKSPACE"/hyperos_port/out/$ROM_FILE $ROM_FILE
          ls -al "$GITHUB_WORKSPACE"/hyperos_port/GithubRelease/
     
      - name: 9. PUSH ROM TO ONEDRIVE
        if:  ${{  github.event.inputs.ONEDRIVE == 'TRUE' }}
        run: |
            rclone sync -P "$GITHUB_WORKSPACE"/hyperos_port/out/${{ env.ROM_FILE }} onedrive:/ROM/github-actions/$OS_VERSION
            SHARE_LINK=$(rclone link onedrive:/ROM/github-actions/ --onedrive-link-scope anonymous)
            touch file.log
            echo -e "Onedrive alternate download link: \n $SHARE_LINK" > file.log
     
      - name: 10. UPLOAD ROM TO GITHUB RELEASE
        if: ${{  github.event.inputs.GITHUBRELEASE == 'TRUE' }}
        uses: ncipollo/release-action@main
        with:
          artifacts: ${{ github.workspace }}/hyperos_port/GithubRelease/*
          name: ${{ env.OS_VERSION }}
          tag: ${{ env.OS_VERSION }}
          bodyFile: "${{ github.workspace }}/file.log"
          allowUpdates: true
          artifactErrorsFailBuild: true
