name: test_zerotier
on:
  workflow_dispatch:
    inputs:
      DOWNLOAD_URL:
        description: "待转移的xiaomi.eu底包下载地址，多个通过逗号分隔"
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 1. 最大化并挂载构建空间 | MAXIMIZE BUILD SPACE
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 8192
          root-reserve-mb: 4096
          temp-reserve-mb: 4096
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: 2. 检出仓库文件 | CHECKOUT REPOSITORY
        uses: actions/checkout@main
        with:
          ref: main
          fetch-depth: 1
      - name: 3. 准备环境 | PREPARE ENVIRONMENT
        run: |
          sudo apt install aria2
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone/
          echo "${{ secrets.RCLONE_TOKEN }}" > token.txt
          base64 -d token.txt > ~/.config/rclone/rclone.conf
      - name: 4. 下载 | START DOWNLOAD
        run: |
          mkdir roms
          cd roms
          IFS=','
          read -ra links <<< ${{ github.event.inputs.DOWNLOAD_URL }}
          for link in "${links[@]}"; do
            echo "Downloding $link"
            aria2c --max-download-limit=1024M --file-allocation=none -s10 -x10 -j10 $link
          done
      - name: 5. 安装 ZeroTier | Install Zerotier
        uses: zerotier/github-action@v1
        with:
          network_id: ${{ secrets.NETWORK_ID }}
      - name: 6. Ping测试 | ping host
        shell: bash
        run: |
          count=5
          while ! ping -c 1 ${{ secrets.SMB_IP }} ; do
          echo "waiting..." ;
          sleep 1 ;
          let count=count-1
          done
          echo "ping success"
      - name: 6. 传送测试 | Transfer test
        run: |
          rclone sync onedrive:ROM_FILES/cas.zip smb:backup/test/ --progress
